resolver: lts-6.30
compiler: ghcjs-0.2.0.9006030_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006030_ghc-7.10.3:
        url: http://ghcjs.tolysz.org/lts-6.30-9006030.tar.gz
        sha1: 2371e2ffe9e8781808b7a04313e6a0065b64ee51

allow-newer: true

packages:
- '.'

- location:
    git: https://github.com/d0kt0r0/MusicW.git
    commit: f2f7e7796f26facb83ed3d80bc0f0f6661208294
  extra-dep: true
  
extra-deps:
- ghcjs-dom-0.2.3.1
- reflex-dom-0.3
- reflex-0.4.0
- ref-tf-0.4
