resolver: lts-9.21
compiler: ghcjs-0.2.1.9009021_ghc-8.0.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9009021_ghc-8.0.2:
           url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9009021.tar.gz
           sha1: b1740c3c99e5039ac306702894cd6e58283f4d31

allow-newer: true

packages:
- '.'

- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: 2c089a255184ac1ae8250be44dcb44fddad7ddd5
  extra-dep: true

- location:
    git: https://github.com/reflex-frp/reflex-dom.git
    commit: 8bde2d72193369c92a995820ca1f56690d3c8ec3
  subdirs:
  - reflex-dom-core
  - reflex-dom
  extra-dep: true

- location:
    git: https://github.com/d0kt0r0/MusicW.git
    commit: e8f084fe949c39ec77e4e1756ab14cb6be587387
  extra-dep: true

extra-deps:
  - prim-uniq-0.1.0.1
  - ref-tf-0.4.0.1
  - ghcjs-dom-0.9.2.0
  - ghcjs-dom-jsffi-0.9.2.0
  - dependent-sum-template-0.0.0.6
  - jsaddle-0.9.5.0
  - zenc-0.1.1
  - monoidal-containers-0.4.0.0
